# Generated by Django 5.1.1 on 2024-10-16 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('email', models.EmailField(default='admin@kku.ac.th', max_length=100)),
                ('password', models.CharField(default='admin1234', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=17)),
                ('password', models.CharField(max_length=20)),
                ('employee_id', models.CharField(max_length=10)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('kkumail', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=17)),
                ('password', models.CharField(max_length=20)),
                ('student_id_edu', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=100)),
                ('borrow_ed', models.IntegerField(default=0)),
                ('borrow_ing', models.IntegerField(default=0)),
                ('return_ed', models.IntegerField(default=0)),
                ('not_return', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='media/images/default.jpg', upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('parcel_id', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('date_borrow', models.DateField(blank=True, help_text='Date when the item was borrowed', null=True)),
                ('date_return', models.DateField(blank=True, help_text='Date when the item is returned', null=True)),
                ('describtion', models.CharField(default='No infomation found.', max_length=360)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_on', models.DateTimeField(blank=True, null=True)),
                ('returned_on', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipment')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('parcel_id',), name='unique_parcel_id'),
        ),
    ]
