# Generated by Django 5.1.2 on 2024-10-19 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuringBorrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_on', models.DateTimeField(blank=True, null=True)),
                ('returned_on', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipment')),
            ],
        ),
    ]
