# Generated by Django 5.1.2 on 2024-10-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_duringborrowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='duringborrowing',
            name='is_during',
            field=models.BooleanField(default=False),
        ),
    ]
