# Generated by Django 5.1.2 on 2024-10-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_duringborrowing_is_during'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
