# Generated by Django 5.1.2 on 2024-10-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_admin_is_staff_staff_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='not_return',
            new_name='late_return',
        ),
    ]
