# Generated by Django 5.1.2 on 2024-10-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_not_return_student_late_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrowed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='returned_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duringborrowing',
            name='borrowed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duringborrowing',
            name='returned_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
