# Generated by Django 5.1.2 on 2024-10-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_admin_is_superuser_staff_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='categories',
            field=models.CharField(default='default', max_length=360),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
